import 'dart:ui';
import 'package:flame/collisions.dart';
import 'package:flame/components.dart';
import '../tr_game.dart';
import 'progress.dart';


class Player extends SpriteAnimationComponent with CollisionCallbacks, HasGameReference<TRGame> {

  Player(Progress progress) : playerProgress = progress;
  //player will be generated by trgame with progress as input

  Progress playerProgress;

  @override
  Future<void> onLoad() async{
    
  }

  @override
  void render(Canvas canvas) {
    //should render different things on condition, like in card
    //if player got hit by enemy, play hit animation
    //if player just placed a card, play attack animation
    //else just a player standing there
    
    //and if there's time i can add a few "idle" sprites like looking at his nails waiting for player input
  }
}